// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(NostalgiaTVContext))]
    [Migration("20261007040734_AddEpisodeAvailability")]
    partial class AddEpisodeAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Entities.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelBumper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelEraId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelEraId");

                    b.ToTable("ChannelBumpers");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ChannelId", "Status", "CreatedAtUtc");

                    b.ToTable("ChannelComments");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HistoricalEndDate");

                    b.Property<string>("FolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HistoricalStartDate");

                    b.HasKey("Id");

                    b.ToTable("ChannelEras", t =>
                        {
                            t.HasCheckConstraint("CK_ChannelEras_HistoricalDates", "[HistoricalEndDate] IS NULL OR [HistoricalEndDate] >= [HistoricalStartDate]");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraBreakRule", b =>
                {
                    b.Property<int>("ChannelEraId")
                        .HasColumnType("int");

                    b.Property<int>("MaximumAds")
                        .HasColumnType("int");

                    b.Property<int>("MaximumBreakSeconds")
                        .HasColumnType("int");

                    b.Property<int>("MinimumAds")
                        .HasColumnType("int");

                    b.HasKey("ChannelEraId");

                    b.ToTable("ChannelEraBreakRules", t =>
                        {
                            t.HasCheckConstraint("CK_ChannelEraBreakRules_AdCount", "[MinimumAds] >= 1 AND [MaximumAds] >= [MinimumAds]");

                            t.HasCheckConstraint("CK_ChannelEraBreakRules_Duration", "[MaximumBreakSeconds] > 0");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraInterlude", b =>
                {
                    b.Property<int>("ChannelEraId")
                        .HasColumnType("int");

                    b.Property<int>("InterludeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MinimumGapSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ChannelEraId", "InterludeId", "Role");

                    b.HasIndex("InterludeId");

                    b.ToTable("ChannelEraInterludes", t =>
                        {
                            t.HasCheckConstraint("CK_ChannelEraInterludes_Gap", "[MinimumGapSeconds] >= 0");

                            t.HasCheckConstraint("CK_ChannelEraInterludes_Role", "[Role] IN ('BreakOpener', 'Advertisement', 'BreakCloser')");

                            t.HasCheckConstraint("CK_ChannelEraInterludes_Weight", "[Weight] > 0");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraSelectedSeason", b =>
                {
                    b.Property<int>("ChannelEraId")
                        .HasColumnType("int")
                        .HasColumnName("ChannelErasId");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.HasKey("ChannelEraId", "SeriesId", "SeasonNumber");

                    b.ToTable("ChannelEraSelectedSeasons", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChannelEraSelectedSeasons_SeasonNumber", "[SeasonNumber] >= 0");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraSelection", b =>
                {
                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelEraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SelectedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ChannelId");

                    b.HasIndex("ChannelId", "ChannelEraId");

                    b.ToTable("ChannelEraSelections");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraSeries", b =>
                {
                    b.Property<int>("ChannelEraId")
                        .HasColumnType("int")
                        .HasColumnName("ChannelErasId");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<bool>("HasSeasonFilter")
                        .HasColumnType("bit");

                    b.HasKey("ChannelEraId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("ChannelEraSeries", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelScheduleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BumperId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int?>("ShuffleCycle")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BumperId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("ChannelScheduleEntries");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEpisodeId")
                        .HasColumnType("int");

                    b.Property<double>("CurrentSecond")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("CurrentEpisodeId");

                    b.ToTable("ChannelStates");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeTypeId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("ApplicationCore.Entities.EpisodeBreakPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OffsetSeconds")
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId", "OffsetSeconds")
                        .IsUnique();

                    b.ToTable("EpisodeBreakPoints", t =>
                        {
                            t.HasCheckConstraint("CK_EpisodeBreakPoints_Offset", "[OffsetSeconds] > 0");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.EpisodeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EpisodeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Regular"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Special"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Christmas Special"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Halloween Special"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Movie"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Interlude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApprovedForBroadcast")
                        .HasColumnType("bit");

                    b.Property<decimal>("DurationSeconds")
                        .HasColumnType("decimal(12,3)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OriginalYearFrom")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalYearTo")
                        .HasColumnType("int");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Interludes", t =>
                        {
                            t.HasCheckConstraint("CK_Interludes_Duration", "[DurationSeconds] > 0");

                            t.HasCheckConstraint("CK_Interludes_Kind", "[Kind] IN ('Bumper', 'Advertisement')");

                            t.HasCheckConstraint("CK_Interludes_OriginalYears", "[OriginalYearTo] IS NULL OR [OriginalYearFrom] IS NULL OR [OriginalYearTo] >= [OriginalYearFrom]");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.MediaProcessingJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SourceModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long>("SourceSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Worker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Worker", "Fingerprint")
                        .IsUnique();

                    b.HasIndex("Worker", "Status", "Id");

                    b.ToTable("MediaProcessingJobs");
                });

            modelBuilder.Entity("ApplicationCore.Entities.MediaResourcePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppliedCores")
                        .HasColumnType("int");

                    b.Property<int>("AvailableCores")
                        .HasColumnType("int");

                    b.Property<int>("DayCores")
                        .HasColumnType("int");

                    b.Property<int>("NightCores")
                        .HasColumnType("int");

                    b.Property<bool>("NightEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("NightEndMinute")
                        .HasColumnType("int");

                    b.Property<int>("NightStartMinute")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MediaResourcePolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliedCores = 0,
                            AvailableCores = 0,
                            DayCores = 1,
                            NightCores = 3,
                            NightEnabled = true,
                            NightEndMinute = 300,
                            NightStartMinute = 0,
                            TimeZoneId = "America/Guatemala"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.MediaWorkerState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HeartbeatUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MediaWorkerStates");

                    b.HasData(
                        new
                        {
                            Id = "transcode",
                            Enabled = false
                        },
                        new
                        {
                            Id = "index",
                            Enabled = false
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Caption = "SEGURIDAD",
                            Icon = "security",
                            IsVisible = true,
                            Name = "Seguridad",
                            SortOrder = 1,
                            Url = ""
                        },
                        new
                        {
                            Id = 1,
                            Caption = "CONTENIDO",
                            Icon = "movie",
                            IsVisible = true,
                            Name = "Contenido",
                            SortOrder = 2,
                            Url = ""
                        },
                        new
                        {
                            Id = 6,
                            Caption = "Roles",
                            Icon = "admin_panel_settings",
                            IsVisible = true,
                            Name = "Roles",
                            ParentId = 2,
                            SortOrder = 1,
                            Url = "/dashboard/roles"
                        },
                        new
                        {
                            Id = 7,
                            Caption = "Usuarios",
                            Icon = "people",
                            IsVisible = true,
                            Name = "Users",
                            ParentId = 2,
                            SortOrder = 2,
                            Url = "/dashboard/users"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Series",
                            Icon = "movie",
                            IsVisible = true,
                            Name = "Series",
                            ParentId = 1,
                            SortOrder = 1,
                            Url = "/dashboard/series"
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Episodios",
                            Icon = "video_library",
                            IsVisible = true,
                            Name = "Episodes",
                            ParentId = 1,
                            SortOrder = 2,
                            Url = "/dashboard/episodes"
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Canales",
                            Icon = "live_tv",
                            IsVisible = true,
                            Name = "Channels",
                            ParentId = 1,
                            SortOrder = 3,
                            Url = "/dashboard/channels"
                        },
                        new
                        {
                            Id = 8,
                            Caption = "Categorías",
                            Icon = "category",
                            IsVisible = true,
                            Name = "Categories",
                            ParentId = 1,
                            SortOrder = 4,
                            Url = "/dashboard/categories"
                        },
                        new
                        {
                            Id = 9,
                            Caption = "Eras",
                            Icon = "history_edu",
                            IsVisible = true,
                            Name = "Channel Eras",
                            ParentId = 1,
                            SortOrder = 5,
                            Url = "/dashboard/channel-eras"
                        },
                        new
                        {
                            Id = 10,
                            Caption = "Bumpers",
                            Icon = "movie_filter",
                            IsVisible = true,
                            Name = "Channel Bumpers",
                            ParentId = 1,
                            SortOrder = 6,
                            Url = "/dashboard/channel-bumpers"
                        },
                        new
                        {
                            Id = 11,
                            Caption = "Transcodificación",
                            Icon = "video_settings",
                            IsVisible = true,
                            Name = "Transcoding",
                            ParentId = 1,
                            SortOrder = 7,
                            Url = "/dashboard/transcoding"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.MetadataImportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SeriesExternalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("SeriesExternalId");

                    b.ToTable("MetadataImportRuns");
                });

            modelBuilder.Entity("ApplicationCore.Entities.MetadataProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MetadataProviders");
                });

            modelBuilder.Entity("ApplicationCore.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full access",
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScheduledAdBreak", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EpisodeBreakPointId")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<long>("ScheduledProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeBreakPointId");

                    b.HasIndex("ScheduledProgramId", "EpisodeBreakPointId")
                        .IsUnique();

                    b.HasIndex("ScheduledProgramId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ScheduledAdBreaks", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduledAdBreaks_Ordinal", "[Ordinal] > 0");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScheduledPlaybackSegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InterludeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MediaEndSecond")
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal?>("MediaStartSecond")
                        .HasColumnType("decimal(12,3)");

                    b.Property<long?>("ScheduledAdBreakId")
                        .HasColumnType("bigint");

                    b.Property<long>("ScheduledProgramId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InterludeId");

                    b.HasIndex("ScheduledAdBreakId", "ScheduledProgramId");

                    b.HasIndex("ScheduledProgramId", "Sequence")
                        .IsUnique();

                    b.HasIndex("StartsAtUtc", "EndsAtUtc");

                    b.ToTable("ScheduledPlaybackSegments", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduledPlaybackSegments_Content", "([InterludeId] IS NULL AND [ScheduledAdBreakId] IS NULL AND [MediaStartSecond] IS NOT NULL AND [MediaEndSecond] IS NOT NULL AND [MediaStartSecond] >= 0 AND [MediaEndSecond] > [MediaStartSecond]) OR ([InterludeId] IS NOT NULL AND [ScheduledAdBreakId] IS NOT NULL AND [MediaStartSecond] IS NULL AND [MediaEndSecond] IS NULL)");

                            t.HasCheckConstraint("CK_ScheduledPlaybackSegments_Sequence", "[Sequence] > 0");

                            t.HasCheckConstraint("CK_ScheduledPlaybackSegments_Time", "[EndsAtUtc] > [StartsAtUtc]");
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScheduledProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChannelEraId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShuffleCycle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelEraId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("ScheduledPrograms");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Seasons")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SeriesComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("UserId");

                    b.HasIndex("ParentCommentId", "SeriesId");

                    b.ToTable("SeriesComments");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SeriesExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("ProviderId", "ExternalId")
                        .IsUnique();

                    b.ToTable("SeriesExternalIds");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "kvfEh9DsfvFzJseLEA3QIQ==:WSdzlu6ve0AiOFTunKWVTMgQNnCtxd7F8xkEamSy+4Y=",
                            RolId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ViewerDevices");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerPairingCode", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Hash");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("ViewerPairingCodes");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ViewerProfiles");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerProgress", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<double>("CurrentSecond")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ProfileId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("ViewerProgress");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerWatchRange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("EndSecond")
                        .HasColumnType("float");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("StartSecond")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "EpisodeId", "StartSecond");

                    b.ToTable("ViewerWatchRanges");
                });

            modelBuilder.Entity("CategorySeries", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("SeriesCategories", (string)null);
                });

            modelBuilder.Entity("ChannelSeries", b =>
                {
                    b.Property<int>("ChannelsId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("ChannelsId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("ChannelSeries");
                });

            modelBuilder.Entity("MenuRol", b =>
                {
                    b.Property<int>("MenusId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("MenusId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("MenuRol");

                    b.HasData(
                        new
                        {
                            MenusId = 1,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 2,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 3,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 4,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 5,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 6,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 7,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 8,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 9,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 10,
                            RolesId = 1
                        },
                        new
                        {
                            MenusId = 11,
                            RolesId = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelBumper", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ChannelEra", "ChannelEra")
                        .WithMany("Bumpers")
                        .HasForeignKey("ChannelEraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelEra");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelComment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEra", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Channel", "Channel")
                        .WithMany("Eras")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraBreakRule", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ChannelEra", null)
                        .WithOne()
                        .HasForeignKey("ApplicationCore.Entities.ChannelEraBreakRule", "ChannelEraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraInterlude", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ChannelEra", null)
                        .WithMany()
                        .HasForeignKey("ChannelEraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Interlude", null)
                        .WithMany()
                        .HasForeignKey("InterludeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraSelectedSeason", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ChannelEraSeries", "ChannelEraSeries")
                        .WithMany("SelectedSeasons")
                        .HasForeignKey("ChannelEraId", "SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelEraSeries");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraSelection", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Channel", null)
                        .WithOne()
                        .HasForeignKey("ApplicationCore.Entities.ChannelEraSelection", "ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.ChannelEra", null)
                        .WithMany()
                        .HasForeignKey("ChannelId", "ChannelEraId")
                        .HasPrincipalKey("ChannelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraSeries", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ChannelEra", "ChannelEra")
                        .WithMany("SeriesLinks")
                        .HasForeignKey("ChannelEraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelEra");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelScheduleEntry", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ChannelBumper", "Bumper")
                        .WithMany()
                        .HasForeignKey("BumperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApplicationCore.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bumper");

                    b.Navigation("Channel");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelState", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Channel", "Channel")
                        .WithOne("State")
                        .HasForeignKey("ApplicationCore.Entities.ChannelState", "ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Episode", "CurrentEpisode")
                        .WithMany()
                        .HasForeignKey("CurrentEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("CurrentEpisode");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Episode", b =>
                {
                    b.HasOne("ApplicationCore.Entities.EpisodeType", "EpisodeType")
                        .WithMany()
                        .HasForeignKey("EpisodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Series", "Series")
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EpisodeType");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ApplicationCore.Entities.EpisodeBreakPoint", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.MediaProcessingJob", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.MediaWorkerState", null)
                        .WithMany()
                        .HasForeignKey("Worker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.Menu", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ApplicationCore.Entities.MetadataImportRun", b =>
                {
                    b.HasOne("ApplicationCore.Entities.SeriesExternalId", null)
                        .WithMany()
                        .HasForeignKey("SeriesExternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.RefreshToken", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScheduledAdBreak", b =>
                {
                    b.HasOne("ApplicationCore.Entities.EpisodeBreakPoint", "EpisodeBreakPoint")
                        .WithMany()
                        .HasForeignKey("EpisodeBreakPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.ScheduledProgram", "ScheduledProgram")
                        .WithMany()
                        .HasForeignKey("ScheduledProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EpisodeBreakPoint");

                    b.Navigation("ScheduledProgram");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScheduledPlaybackSegment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Interlude", "Interlude")
                        .WithMany()
                        .HasForeignKey("InterludeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApplicationCore.Entities.ScheduledProgram", "ScheduledProgram")
                        .WithMany()
                        .HasForeignKey("ScheduledProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.ScheduledAdBreak", null)
                        .WithMany()
                        .HasForeignKey("ScheduledAdBreakId", "ScheduledProgramId")
                        .HasPrincipalKey("Id", "ScheduledProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Interlude");

                    b.Navigation("ScheduledProgram");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ScheduledProgram", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ChannelEra", "ChannelEra")
                        .WithMany()
                        .HasForeignKey("ChannelEraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChannelEra");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SeriesComment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.SeriesComment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId", "SeriesId")
                        .HasPrincipalKey("Id", "SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ApplicationCore.Entities.SeriesExternalId", b =>
                {
                    b.HasOne("ApplicationCore.Entities.MetadataProvider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerDevice", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ViewerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerPairingCode", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ViewerDevice", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerProgress", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.ViewerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.ViewerWatchRange", b =>
                {
                    b.HasOne("ApplicationCore.Entities.ViewerProgress", null)
                        .WithMany()
                        .HasForeignKey("ProfileId", "EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategorySeries", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChannelSeries", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuRol", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.Channel", b =>
                {
                    b.Navigation("Eras");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEra", b =>
                {
                    b.Navigation("Bumpers");

                    b.Navigation("SeriesLinks");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChannelEraSeries", b =>
                {
                    b.Navigation("SelectedSeasons");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Series", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
